apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-tekton
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: "10"
    spec:
      containers:
        - image: 192.168.1.52/system_containers/tekton/helloworld:v0.1.0
        #- image: 192.168.1.52/system_containers/gcr.cn/knative-samples/helloworld-go
