apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: tekton-blue-green
  namespace: default
spec:
  template:
    metadata:
      name: tekton-blue-green-2
    spec:
      containers:
      - image: 192.168.1.52/system_containers/gcr.cn/knative-samples/knative-route-demo:green
        env:
          - name: T_VERSION
            value: "green"
  traffic:
  - tag: current
    revisionName: tekton-blue-green-1
    percent: 100
  - tag: latest
    latestRevision: true
    percent: 0
